<a href="https://colab.research.google.com/github/Gibbsfam7/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/AnnalisaGibbsFeatures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://resources.lendingclub.com/LoanStats_2019Q1.csv.zip

--2019-07-20 00:15:12--  https://resources.lendingclub.com/LoanStats_2019Q1.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2019Q1.csv.zip.2’

LoanStats_2019Q1.cs     [     <=>            ]  19.30M   875KB/s    in 23s

2019-07-20 00:15:35 (867 KB/s) - ‘LoanStats_2019Q1.csv.zip.2’ saved [20240936]

In [2]:
!unzip LoanStats_2019Q1.csv.zip

Archive:  LoanStats_2019Q1.csv.zip
replace LoanStats_2019Q1.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [3]:
!head LoanStats_2019Q1.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","20000","20000","20000"," 60 months"," 17.19%","499.1","C","C5","Front desk supervisor","6 years","RENT","47000","Source Verified","Mar-2019","Current","n","","","debt_consolidation","Debt consolidation","958xx","CA","14.02","0","Sep-2006","1","50","","15","0","10687","19.7%","53","w","19254.76","19254.76","1459.1","1459.10","745.24","713.86","0.0","0.0","0.0","Jun-2019","499.1","Jul-2019","Jun-2019","0","50","1","Individual","","","","0","0","31546","3","2","1","2","10","20859","97","4","9","5909","42","54300","6","1","3","11","2103","23647","30","0","0","150","100","1","1","0","5","","3","50","3","3","4","8","19","19","13","33","4","15","0","0","0","5","98","12.5","0","0","75824","31546","33800","21524","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","12000","12000","12000"," 36 months"," 16.40%","424.26","C","C4","Executive Director","4 years","MORTGAGE","95000","Not Verified","Mar-2019","Current","n","","","debt_consolidation","Debt consolidation","436xx","OH","29.5","0","Nov-1992","0","29","","19","0","16619","64.9%","36","w","11475.92","11475.92","826.65","826.65","524.08","302.57","0.0","0.0","0.0","May-2019","424.26","Jul-2019","Jun-2019","0","30","1","Individual","","","","0","0","176551","1","5","2","5","7","35115","65","3","6","4899","65","25600","4","0","3","12","9292","3231","82.5","0","0","316","269","5","5","2","12","58","7","29","1","6","8","6","9","10","13","23","8","19","0","0","0","6","80.6","66.7","0","0","209488","51734","18500","54263","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","3000","3000","3000"," 36 months"," 14.74%","103.62","C","C2","Office Manager","4 years","MORTGAGE","58750","Verified","Mar-2019","Current","n","","","medical","Medical expenses","327xx","FL","30.91","0","Jun-2004","0","24","","16","0","20502","60.1%","25","f","2865.64","2865.64","202.33","202.33","134.36","67.97","0.0","0.0","0.0","May-2019","103.62","Jul-2019","Jun-2019","0","","1","Individual","","","","0","0","37816","0","3","0","0","27","17314","48","0","0","3962","54","34100","0","1","0","0","2364","1208","89.4","0","0","177","164","35","27","4","40","24","","24","0","7","12","7","8","6","13","15","12","16","0","0","0","0","96","71.4","0","0","69911","37816","11400","35811","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","35000","35000","35000"," 36 months"," 15.57%","1223.08","C","C3","Store Manager ","10+ years","RENT","122000","Verified","Mar-2019","Current","n","","","credit_card","Credit card refinancing","333xx","FL","22","1","Dec-2009","0","20","","5","0","1441","24.4%","18","w","33459.43","33459.43","2446.76","2446.76","1540.57","845.04","61.15","0.0","0.0","Jun-2019","1223.08","Jul-2019","Jun-2019","0","20","1","Individual","","","","0","0","24471","0","3","0","0","26","23030","39","0","0","1441","37","5900","2","4","1","1","4894","159","90.1","0","0","108","111","52","24","0","85","","9","","1","1","1","1","3","10","2","7","1","5","0","0","1","0","94.4","100","0","0","65640","24471","1600","59740","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 15.57%","174.73","C","C3","Area Manager","3 years","OWN","65000","Verified","Mar-2019","Current","n","","","house","Home buying","640xx","MO","16.28","1","Jul-2001","0","7","","9","0","5604","64.4%","25","w","4778.86","4778.86","340.81","340.81","221.14","119.67","0.0","0.0","0.0","May-2019","174.73","Jul-2019","Jun-2019","0","7","1","Individual","","","","0","0","29775","0","1","0","1","17","24171","82","1","6","1824","78","8700","1","0","0","7","3722","1070","75.7","0","0","111","212","10","10","4","17","69","17","69","4","3","5","5","9","7","8","14","5","9","0","0","1","1","76","50","0","0","38190","29775","4400","29490","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","40000","40000","40000"," 60 months"," 12.40%","897.89","B","B4","SVP","10+ years","MORTGAGE","515000","Source Verified","Mar-2019","Current","n","","","debt_consolidation","Debt consolidation","117xx","NY","18.19","0","Feb-1993","1","","","24","0","130490","86.4%","49","w","39025.88","39025.88","1740.67","1740.67","974.12","766.55","0.0","0.0","0.0","May-2019","897.89","Jul-2019","Jun-2019","0","","1","Individual","","","","0","205","569565","3","6","2","3","4","72207","39","3","3","20896","67","151100","1","6","2","7","23732","4733","94.8","0","0","160","304","3","3","6","10","","0","","0","10","14","10","17","12","15","28","14","24","0","0","0","5","100","100","0","0","752911","204997","90800","144678","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","40000","40000","40000"," 60 months"," 11.02%","870.1","B","B2","VP of Sales","3 years","MORTGAGE","288000","Not Verified","Mar-2019","Current","n","","","credit_card","Credit card refinancing","843xx","UT","19.74","0","May-2002","0","","","20","0","66240","43.9%","34","w","38989.85","38989.85","1691.22","1691.22","1010.15","681.07","0.0","0.0","0.0","May-2019","870.1","Jul-2019","Jun-2019","0","","1","Individual","","","","0","0","390598","0","5","0","2","16","140633","58","0","2","22577","49","150900","0","6","1","4","19530","81923","43.1","0","0","136","202","17","16","1","17","","3","","0","8","9","10","15","11","13","22","10","20","0","0","0","0","100","20","0","0","543401","206873","143900","197751","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","20000","20000","20000"," 60 months"," 12.40%","448.95","B","B4","Sales","1 year","MORTGAGE","70000","Source Verified","Mar-2019","Current","n","","","credit_card","Credit card refinancing","481xx","MI","32.33","0","May-1995","0","","","12","0","31036","56.7%","32","w","19512.93","19512.93","870.34","870.34","487.07","383.27","0.0","0.0","0.0","May-2019","448.95","Jul-2019","Jun-2019","0","","1","Joint App","102400","31.16","Source Verified","0","0","204292","0","3","0","1","14","16305","33","0","0","17389","46","54700","1","3","0","2","17024","268","98.9","0","0","133","286","41","14","4","84","","15","","0","3","7","3","7","9","8","19","7","12","0","0","0","0","100","100","0","0","267991","47341","24800","49291","56647","May-1995","0","4","15","61.3","1","31","0","0","","N","","","","","","","","","","","","","","","N","","","","","",""

In [4]:
import pandas as pd
df = pd.read_csv('LoanStats_2019Q1.csv', skiprows=1, skipfooter=2, engine='python')
print(df.shape)
df.head()

(115675, 144)

   id  member_id  ...  settlement_percentage  settlement_term
0 NaN        NaN  ...                    NaN              NaN
1 NaN        NaN  ...                    NaN              NaN
2 NaN        NaN  ...                    NaN              NaN
3 NaN        NaN  ...                    NaN              NaN
4 NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [22]:
column = 144
print(column)

144

In [23]:
#I'm not sure if this is what the assignment is asking for?
int_col = int(column)
print(int_col)

144

In [28]:
#I'm not understanding how to process this. 
import numpy as np
#def loan_status(x):
  #if isinstance(int=1):
  #  return x
  #else:
   # return '0'
df['loan_status_is_great']= np.where(int = 1, 'Current',
                                    int = 0, '0')

SyntaxError: ignored

In [21]:
#last_month = {'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec'}
#not sure how to set the condition
df['last_pymnt_d_month'] = 'Nan'
df['last_pymnt_d_years'] = 'Nan'

df.head(10)

   id  member_id  ...  last_pymnt_d_month  last_pymnt_d_years
0 NaN        NaN  ...                 Nan                 Nan
1 NaN        NaN  ...                 Nan                 Nan
2 NaN        NaN  ...                 Nan                 Nan
3 NaN        NaN  ...                 Nan                 Nan
4 NaN        NaN  ...                 Nan                 Nan
5 NaN        NaN  ...                 Nan                 Nan
6 NaN        NaN  ...                 Nan                 Nan
7 NaN        NaN  ...                 Nan                 Nan
8 NaN        NaN  ...                 Nan                 Nan
9 NaN        NaN  ...                 Nan                 Nan

[10 rows x 146 columns]